# sigmoid

In [1]:
import tensorflow as tf

In [9]:
a = tf.constant([4.0, 1.0, 3.0], dtype=tf.float32)
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 1., 3.], dtype=float32)>

In [10]:
b= tf.keras.activations.sigmoid(a)
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)>

In [11]:
b.numpy()

array([0.98201376, 0.7310586 , 0.95257413], dtype=float32)

# softmax

In [13]:
inputs = tf.random.normal(shape=(1, 3))
inputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.26849222,  0.10720734,  2.9188383 ]], dtype=float32)>

In [14]:
outputs = tf.keras.activations.softmax(inputs)
outputs

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.0374817 , 0.05457371, 0.90794456]], dtype=float32)>

In [15]:
outputs.numpy()
# softmax를 사용하면 합산값이 1을 넘지 않음

array([[0.0374817 , 0.05457371, 0.90794456]], dtype=float32)

In [17]:
0.0374817+0.05457371+0.90794456

0.99999997