In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [3]:
import pandas as pd
df_iris = pd.DataFrame(iris.data)
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [4]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_iris.to_sql('iris_resource', connect, if_exists = 'append', index = False)

In [5]:
df_load = pd.read_sql_query('select * from iris_resource', connect)
df_load.head(4)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2

In [6]:
x_data = df_load.to_numpy()
x_data.shape

(150, 4)

In [7]:
import numpy as np

In [8]:
y_data = iris.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([0, 1, 2]))

# 교육단계

In [9]:
import tensorflow as tf

In [10]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(4,)))     # input layer
model.add(tf.keras.layers.Dense(64, activation='relu'))     # hidden layer
model.add(tf.keras.layers.Dense(24, activation='relu'))     # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax'))     # output layer

model.compile(optimizer='adam', loss='mse', metrics = ['acc'])     # gadget


In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                320       
_________________________________________________________________
dense_1 (Dense)              (None, 24)                1560      
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 75        
Total params: 1,955
Trainable params: 1,955
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_data, y_data, epochs = 50, validation_split = 0.3)   # 학습

Epoch 1/50
4/4 [==============================] - 1s 100ms/step - loss: 0.4210 - acc: 0.4762 - val_loss: 2.7943 - val_acc: 0.0000e+00
Epoch 2/50
4/4 [==============================] - 0s 10ms/step - loss: 0.4055 - acc: 0.7333 - val_loss: 2.7853 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 10ms/step - loss: 0.4007 - acc: 0.4762 - val_loss: 2.7792 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3981 - acc: 0.4857 - val_loss: 2.7782 - val_acc: 0.9778
Epoch 5/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3979 - acc: 0.2286 - val_loss: 2.7789 - val_acc: 1.0000
Epoch 6/50
4/4 [==============================] - 0s 8ms/step - loss: 0.3978 - acc: 0.0476 - val_loss: 2.7785 - val_acc: 0.4667
Epoch 7/50
4/4 [==============================] - 0s 10ms/step - loss: 0.3974 - acc: 0.2857 - val_loss: 2.7787 - val_acc: 0.0000e+00
Epoch 8/50
4/4 [==============================] - 0s 9ms/step - loss: 0.3973 - acc:

# evaluation

In [13]:
model.evaluate(x_data, y_data)

5/5 [==============================] - 0s 3ms/step - loss: 1.1111 - acc: 0.3867


[1.111135482788086, 0.3866666555404663]

# 서비스 단계

In [14]:
x_data[25], y_data[25]

(array([5. , 3. , 1.6, 0.2]), 0)

In [15]:
pred = model.predict([[5. , 3. , 1.6, 0.2]])
pred

array([[0.33371463, 0.32961947, 0.3366659 ]], dtype=float32)

In [17]:
import numpy as np
np.argmax(pred)

2