In [1]:
import tensorflow as tf

In [6]:
loaded_model = tf.keras.models.load_model('./NaverSentimentAnalysis_LSTM.h5')
loaded_model

In [7]:
!python -m pip install konlpy

     |████████████████████████████████| 19.4 MB 6.4 MB/s 
     |████████████████████████████████| 86 kB 6.5 MB/s 
     |████████████████████████████████| 448 kB 57.1 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3


In [8]:
import konlpy

In [10]:
# 불용어 처리
  # words = list()
  # for tok in new_sentence:
  #   if tok not in stopwords:
  #     words.append(tok)

# 한줄로 표현 가능
# --> new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]

In [9]:
import pickle

In [12]:
stopwords = pickle.load(open('./stopwords.pkl','rb'))
print(stopwords)

['의', '가', '이', '은', '들', '는', '좀', '잘', '걍', '과', '도', '를', '으로', '자', '에', '와', '한', '하다']


In [24]:
# 감독이 예술이네. --> 웹 사용자가 입력 (긍정/부정 확인)
okt = konlpy.tag.Okt()
new_sentence = okt.morphs('감독이 예술이네.', stem=True)
new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
new_sentence

['감독', '예술', '이네', '.']

In [25]:
tokenizer = pickle.load(open('./tokenizer.pkl','rb'))
tokenizer

In [27]:
# encoded = tokenizer.texts_to_sequences([new_sentence])
# encoded
pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
pad_new

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  92, 128,   1]],
      dtype=int32)

In [29]:
# ['감독이 예술이네.'] --> 웹 사용자가 입력 (긍정/부정 확인)
score = loaded_model.predict(pad_new)
score

array([[0.49802256]], dtype=float32)

In [31]:
if(score > 0.5):
  print('긍정', score*100)
else:
  print('부정',score*100)

부정 [[49.802254]]


In [ ]:
# okt = konlpy.tag.Okt()
# new_sentence = okt.morphs('감독이 예술이네.', stem=True)
# new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
# # new_sentence
# encoded = tokenizer.texts_to_sequences([new_sentence])
# # encoded
# pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
# # pad_new
# score = loaded_model.predict(pad_new)
# # score

In [32]:
def sentiment_predict(sentence):
  okt = konlpy.tag.Okt()
  new_sentence = okt.morphs(sentence, stem=True)
  new_sentence = [ tok for tok in new_sentence if tok not in stopwords ]
  encoded = tokenizer.texts_to_sequences([new_sentence])
  pad_new = tf.keras.preprocessing.sequence.pad_sequences(encoded, maxlen=50)
  score = loaded_model.predict(pad_new)
  return score

In [35]:
words = '이 영화 꽝이네.'
sentiment_predict(words)

array([[0.50109905]], dtype=float32)

In [36]:
words = '영화 좋으니 마음도 좋네요,'
sentiment_predict(words)

array([[0.5101614]], dtype=float32)