In [1]:
!python -m pip install konlpy

In [2]:
# from preprocess import *
import preprocess as pp

In [3]:
path_csv = './ChatBotData.csv_short'
inputs, outputs = pp.load_data(path_csv)
type(inputs), type(outputs)

(list, list)

In [4]:
inputs[10], outputs[10], len(inputs)

('남자친구 교회 데려가고 싶어', '마음을 열 때까지 설득해보세요.', 20)

In [5]:
print(type(inputs), inputs)

<class 'list'> ['가끔 궁금해', '가끔 뭐하는지 궁금해', '가끔은 혼자인게 좋다', '가난한 자의 설움', '가만 있어도 땀난다', '가상화폐 쫄딱 망함', '가스불 켜고 나갔어', '가스불 켜놓고 나온거 같아', '가스비 너무 많이 나왔다.', '가스비 비싼데 감기 걸리겠어', '남자친구 교회 데려가고 싶어', '남자친구 또 운동 갔어', '남자친구 생일인데 뭘 줄까', '남자친구 승진 선물로 뭐가 좋을까?', '남자친구 오늘 따라 훈훈해 보인다', '남자친구 오늘 좀 질린다.', '남자친구가 나 안 믿어줘', '남자친구가 너무 바빠', '남자친구가 너무 운동만 해', '남자친구가 너무 잘생겼어']


In [7]:
path_vocab = './vocabulary.txt'
char2idx, idx2char, vocab_size = pp.load_vocabulary(path_csv, path_vocab)
type(char2idx), type(idx2char), type(vocab_size)

(dict, dict, int)

In [8]:
print(char2idx)
print(idx2char)
print(vocab_size)

{'<PAD>': 0, '<SOS>': 1, '<END>': 2, '<UNK>': 3, '운동': 4, '가상화폐': 5, '나온거': 6, '있어도': 7, '적당히': 8, '오늘': 9, '것': 10, '좋을': 11, '돈은': 12, '운동만': 13, '걸리겠어': 14, '훈훈해': 15, '달에는': 16, '빨리': 17, '전생에': 18, '데려가고': 19, '가난한': 20, '혼자를': 21, '생일인데': 22, '너무': 23, '쫄딱': 24, '때까지': 25, '같아': 26, '뭐가': 27, '생각해보세요': 28, '켜놓고': 29, '자의': 30, '좀': 31, '거예요': 32, '잘생겼어': 33, '운동을': 34, '좋다': 35, '구하셨나요': 36, '그': 37, '사세요': 38, '빠를수록': 39, '선물로': 40, '가끔': 41, '필요했던': 42, '같아요': 43, '사람도': 44, '갔어': 45, '평소에': 46, '마세요': 47, '식혀주세요': 48, '새출발': 49, '해보세요': 50, '즐기세요': 51, '따라': 52, '끄고': 53, '좋을까': 54, '승진': 55, '결단은': 56, '어서': 57, '들어올': 58, '나갔어': 59, '바빠': 60, '열': 61, '망함': 62, '궁금해': 63, '거짓말': 64, '남자친구가': 65, '땀을': 66, '가스불': 67, '돌아가서': 68, '게': 69, '남자친구': 70, '비싼데': 71, '나오세요': 72, '따뜻하게': 73, '나': 74, '좋아요': 75, '많이': 76, '가스비': 77, '집착하지': 78, '땀난다': 79, '뭐하는지': 80, '다시': 81, '더': 82, '해': 83, '보인다': 84, '하세요': 85, '나라를': 86, '필요한': 87, '마음을': 88, '나왔다': 89, '잊고': 90, '안': 91, '믿어줘':

In [10]:
idx_inputs, input_seq_len = pp.enc_processing(inputs, char2idx)
type(idx_inputs), len(input_seq_len)

(numpy.ndarray, 20)

In [11]:
idx_inputs[3:5]

array([[ 20,  30, 107,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 93,   7,  79,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [14]:
idx_outputs, output_seq_len = pp.dec_output_processing(outputs, char2idx)
type(idx_outputs), len(output_seq_len)

(numpy.ndarray, 20)

In [15]:
idx_outputs[3:5]

array([[ 1, 12, 81, 58, 32,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1, 66, 48,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [16]:
idx_targets = pp.dec_target_processing(outputs, char2idx)
type(idx_targets), len(idx_targets)

(numpy.ndarray, 20)

In [17]:
idx_targets[3:5]

array([[12, 81, 58, 32,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0],
       [66, 48,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [19]:
import numpy as np

In [22]:
np.save(open('./train_inputs.npy', 'wb'), idx_inputs)

In [23]:
np.save(open('./train_outputs.npy', 'wb'), idx_inputs)

In [24]:
np.save(open('./train_targets.npy', 'wb'), idx_inputs)

In [25]:
data_configs = dict()

In [26]:
data_configs['char2idx'] = char2idx
data_configs['idx2char'] = idx2char
data_configs['vocab_size'] = vocab_size

data_configs['pad_symbol'] = '<PAD>'
data_configs['std_symbol'] = '<STD>'
data_configs['end_symbol'] = '<END>'
data_configs['unk_symbol'] = '<UNK>'

In [27]:
pp.json.dump(data_configs, open('./data_config.json', 'w'))