In [2]:
from sklearn import datasets

In [3]:
wine = datasets.load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [5]:
x_data = wine['data']
x_data.shape

(178, 13)

In [ ]:
y_data = wine['target']
y_data

In [9]:
import pandas as pd
df_wine = pd.DataFrame(wine.data)
df_twine = pd.DataFrame(wine.target)
df_wine['y_col'] = df_twine

In [13]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       178 non-null    float64
 1   1       178 non-null    float64
 2   2       178 non-null    float64
 3   3       178 non-null    float64
 4   4       178 non-null    float64
 5   5       178 non-null    float64
 6   6       178 non-null    float64
 7   7       178 non-null    float64
 8   8       178 non-null    float64
 9   9       178 non-null    float64
 10  10      178 non-null    float64
 11  11      178 non-null    float64
 12  12      178 non-null    float64
 13  y_col   178 non-null    int64  
dtypes: float64(13), int64(1)
memory usage: 19.6 KB


In [15]:
import sqlite3
connect = sqlite3.connect('./db.sqlite3')
df_wine.to_sql('wine_resource', connect, if_exists = 'append', index = False)

In [17]:
df_load = pd.read_sql_query('select * from wine_resource', connect)
df_load.head(4)

0     1     2     3      4     5  ...     8     9    10    11      12  y_col
0  14.23  1.71  2.43  15.6  127.0  2.80  ...  2.29  5.64  1.04  3.92  1065.0      0
1  13.20  1.78  2.14  11.2  100.0  2.65  ...  1.28  4.38  1.05  3.40  1050.0      0
2  13.16  2.36  2.67  18.6  101.0  2.80  ...  2.81  5.68  1.03  3.17  1185.0      0
3  14.37  1.95  2.50  16.8  113.0  3.85  ...  2.18  7.80  0.86  3.45  1480.0      0

[4 rows x 14 columns]

In [18]:
x_data = df_load.to_numpy()
x_data.shape

(178, 14)

In [19]:
import numpy as np

In [20]:
y_data = wine.target
y_data, np.unique(y_data)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]), array([0, 1, 2]))

In [21]:
import tensorflow as tf

In [33]:
model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(14,)))     # input layer
model.add(tf.keras.layers.Dense(64, activation='relu'))     # hidden layer
model.add(tf.keras.layers.Dense(32, activation='relu'))     # hidden layer

model.add(tf.keras.layers.Dense(3, activation='softmax'))     # output layer

model.compile(optimizer='adam', loss = 'sparse_categorical_crossentropy', metrics = ['acc'])     # gadget

In [34]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 64)                960       
_________________________________________________________________
dense_10 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_11 (Dense)             (None, 3)                 99        
Total params: 3,139
Trainable params: 3,139
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(x_data, y_data, epochs = 50, validation_split = 0.3)   # 학습

Epoch 1/50
4/4 [==============================] - 1s 57ms/step - loss: 103.0435 - acc: 0.0000e+00 - val_loss: 11.5554 - val_acc: 0.1481
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 46.0116 - acc: 0.4758 - val_loss: 34.9437 - val_acc: 0.0000e+00
Epoch 3/50
4/4 [==============================] - 0s 9ms/step - loss: 25.0498 - acc: 0.4758 - val_loss: 32.5435 - val_acc: 0.0000e+00
Epoch 4/50
4/4 [==============================] - 0s 10ms/step - loss: 5.1767 - acc: 0.5242 - val_loss: 41.0166 - val_acc: 0.1111
Epoch 5/50
4/4 [==============================] - 0s 8ms/step - loss: 7.2504 - acc: 0.5242 - val_loss: 42.0218 - val_acc: 0.0741
Epoch 6/50
4/4 [==============================] - 0s 14ms/step - loss: 3.3370 - acc: 0.5806 - val_loss: 53.7164 - val_acc: 0.0000e+00
Epoch 7/50
4/4 [==============================] - 0s 8ms/step - loss: 5.3439 - acc: 0.4839 - val_loss: 51.0312 - val_acc: 0.0556
Epoch 8/50
4/4 [==============================] - 0s 9ms/step - loss: 1.30

In [36]:
model.evaluate(x_data, y_data)

6/6 [==============================] - 0s 2ms/step - loss: 16.9021 - acc: 0.6404


[16.902057647705078, 0.6404494643211365]

In [37]:
x_data[25], y_data[25]

(array([1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02, 0.000e+00]), 0)

In [38]:
pred = model.predict([[1.305e+01, 2.050e+00, 3.220e+00, 2.500e+01, 1.240e+02, 2.630e+00,
        2.680e+00, 4.700e-01, 1.920e+00, 3.580e+00, 1.130e+00, 3.200e+00,
        8.300e+02, 0.000e+00]])
pred

array([[5.94688542e-02, 9.40531194e-01, 1.19716365e-35]], dtype=float32)

In [39]:
import numpy as np
np.argmax(pred)

1